// The user manual (Help → How do I…, docs/manual/): one page per office action, generated by `npm run manual`
// from the measuring robot's runs (e2e/actions/manual.mjs).
//  • Every action in e2e/actions/actions.json has a page with steps (so a new action can't ship without one).
//  • Help → How do I…: search "deposit", open the page, see numbered steps and a screenshot that loads.
//  • The command bar finds it: "how do I post a deposit" and "help deposit" open the same page.
//  • Print the whole manual (/help?how=all&print=1): every page's heading, grouped, once all pictures loaded.
//  • Light and dark: the page renders in both (MANUAL_SHOTS=dir saves screenshots of each to look at).
/* global document, window */
import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { startApp, launch, signIn, root } from '../lib/server.mjs';

const SHOTS = process.env.MANUAL_SHOTS;
let app; let browser;
before(async () => {
  app = await startApp();
  browser = await launch();
  if (SHOTS) mkdirSync(SHOTS, { recursive: true });
});
after(async () => { await browser?.close(); await app?.stop(); });

const shot = async (page, name) => { if (SHOTS) await page.screenshot({ path: join(SHOTS, `${name}.png`), fullPage: false }); };
const DEPOSIT = 'A084';

test('MANUAL every action has a page with steps', () => {
  const actions = JSON.parse(readFileSync(join(root, 'e2e/actions/actions.json'), 'utf8'));
  const manual = JSON.parse(readFileSync(join(root, 'client/public/manual/manual.json'), 'utf8'));
  const byId = new Map(manual.pages.map((p) => [p.id, p]));
  const missing = actions.filter((a) => !byId.get(a.id)?.steps?.length).map((a) => `${a.id} ${a.name}`);
  assert.deepEqual(missing, [], 'run npm run manual (and add notes to e2e/actions/manual-notes.json for new actions)');
  for (const p of manual.pages) assert.match(p.q, /^How do I .+\?$/, `${p.id} is asked as a question`);
});

for (const scheme of ['light', 'dark']) {
  test(`MANUAL Help → How do I… → search "deposit" → the page with steps and pictures (${scheme})`, async () => {
    const { page, errors, ctx } = await signIn(browser, app.base, { email: 'billing@demo.dentalmachine.app', colorScheme: scheme });
    await page.goto(`${app.base}/help`);
    await page.getByRole('tab', { name: 'How do I…' }).waitFor();
    assert.equal(await page.getByRole('tab', { name: 'How do I…' }).getAttribute('aria-selected'), 'true', 'How do I… is the first thing Help shows');
    await page.locator('.manual-group').first().waitFor();
    await shot(page, `help-index-${scheme}`);
    await page.getByLabel('Search the how-tos').fill('deposit');
    const hit = page.locator('.manual-results a', { hasText: 'daily bank deposit' });
    await hit.waitFor();
    await shot(page, `help-search-${scheme}`);
    await hit.click();
    await page.waitForURL(/how=A084/);
    await page.locator('h1', { hasText: 'How do I make the daily bank deposit?' }).waitFor();
    assert.ok(await page.locator('.manual-steps > li').count() >= 2, 'numbered steps');
    const img = page.locator('.manual-steps img').first();
    await img.scrollIntoViewIfNeeded();
    await page.waitForFunction(() => { const i = document.querySelector('.manual-steps img'); return i && i.complete && i.naturalWidth > 0; });
    assert.equal(await page.evaluate(() => document.documentElement.dataset.theme), scheme);
    assert.ok(await page.getByRole('button', { name: 'Print this page' }).isVisible());
    await page.evaluate(() => window.scrollTo(0, 0));
    await shot(page, `help-page-${scheme}`);
    await img.scrollIntoViewIfNeeded();
    await shot(page, `help-page-steps-${scheme}`);
    if (SHOTS && scheme === 'light') {
      // For a person to look at: the printed page, and a page written by hand (the sensor needs hardware).
      await page.emulateMedia({ media: 'print' });
      await page.evaluate(() => window.scrollTo(0, 0));
      await shot(page, 'help-page-print');
      await page.emulateMedia({ media: 'screen' });
      await page.goto(`${app.base}/help?how=A030`);
      await page.locator('.manual-steps').waitFor();
      await shot(page, 'help-page-by-hand');
      await page.goto(`${app.base}/help`);
      await page.getByRole('button', { name: 'area' }).click();
      await shot(page, 'help-index-by-area');
    }
    assert.deepEqual(errors, []);
    await ctx.close();
  });
}

test('MANUAL the command bar finds the page: "how do I post a deposit" and "help deposit"', async () => {
  const { page, errors, ctx } = await signIn(browser, app.base, { email: 'frontdesk@demo.dentalmachine.app' });
  for (const words of ['how do I post a deposit', 'help deposit']) {
    await page.goto(`${app.base}/`);
    await page.locator('.sidebar').waitFor();
    await page.keyboard.press('Control+k');
    await page.locator('.palette input').waitFor();
    await page.keyboard.type(words);
    const row = page.locator('.palette-item', { hasText: 'How do I make the daily bank deposit?' });
    await row.waitFor();
    await shot(page, `command-bar-${words.replace(/\W+/g, '-')}`);
    await row.click();
    await page.waitForURL(new RegExp(`how=${DEPOSIT}`));
    await page.locator('h1', { hasText: 'How do I make the daily bank deposit?' }).waitFor();
  }
  assert.deepEqual(errors, []);
  await ctx.close();
});

test('MANUAL print the whole manual: every page, grouped by area, pictures loaded', async () => {
  const manual = JSON.parse(readFileSync(join(root, 'client/public/manual/manual.json'), 'utf8'));
  const { page, errors, ctx } = await signIn(browser, app.base, { email: 'admin@demo.dentalmachine.app' });
  await page.goto(`${app.base}/help`);
  const button = page.getByRole('button', { name: 'Print the whole manual' });
  await button.waitFor();
  await button.click();
  await page.waitForURL(/how=all&print=1/);
  await page.locator('.manual-book[data-ready="1"]').waitFor({ timeout: 60_000 });
  const titles = await page.locator('.manual-book-page h1').allTextContents();
  assert.deepEqual([...titles].sort(), manual.pages.map((p) => p.q).sort(), 'every page is in the book');
  assert.equal(await page.locator('.manual-book-area-title').count(), new Set(manual.pages.map((p) => p.area)).size, 'one group per area');
  const broken = await page.evaluate(() => [...document.querySelectorAll('.manual-book img')].filter((i) => !i.complete || !i.naturalWidth).length);
  assert.equal(broken, 0, 'every picture loaded before printing');
  await page.emulateMedia({ media: 'print' });
  await shot(page, 'help-book-print');
  assert.deepEqual(errors, []);
  await ctx.close();
});
